config/routes.rb
Apps::Application.routes.draw do
  get "sessions/new"

  get "users/new"
  get "log_in" => "sessions#new", :as => "log_in" 
  resources :sessions 
  
  namespace :admin do
    resources :books
  end

  resources :articles, :books, :comments
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "books#index"
  resources :users
  get "log_out" => "sessions#destroy", :as => "log_out"
  match 'articles/:id', :to => 'articles#show', :as => "show_article" 
  match 'books/:id', :to => 'books#show', :as => "show_book" 

  match ':controller(/:action(/:id(.:format)))'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :book
  
  attr_accessible :book_id, :comment, :user_id
  validates :comment, :presence => true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_filter :require_login, :only => [:create, :destroy]
  
  def index
    @comments = Comment.all
    respond_to do |format|
      format.html # index.html.erb
      format.rss
    end
  end
  
  def create
    @book = Book.find_by_id(params[:comment][:book_id])
    @comment = @book.comments.create(params[:comment])
    @comments = @book.comments
    respond_to do |format|
      if @comment.save
        format.html { redirect_to(book_path(params[:comment][:book_id]), :notice => 'Comment was successfully created.') }
        format.js
      end
    end
  end

  def destroy
    @comment = Comment.find_by_id(params[:id])
    if @comment.destroy
      flash[:notice] = "Your comment has been deleted"
      redirect_to book_path(params[:book_id])
    else
      flash[:error] = "Your comment is failed to create"
      redirect_to book_path(params[:book_id])
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <span class="dateandoptions">
    Posted <%=time_ago_in_words(comment.created_at)%> ago<br />
    <%= link_to 'Delete', comment_path(comment), :method => :delete, :class => "delete", :remote => true  %>
  </span>
	<p><b><%= comment.name %></b> wrote:</p>
	<br />
  <%= content_tag(:p, comment.body, :class => "comment-body") %>
<% end %>

app/views/comments/create.js.erb
/* Insert a notice between the last comment and the comment form */
$("#comment-notice").html('<div class="flash notice"><%= escape_javascript(flash.delete(:notice)) %></div>');

/* Replace the count of comments */
$("#comments_count").html("<%= pluralize(Comment.count, 'Comment') %>");

/* Add the new comment to the bottom of the comments list */
$("#comments").append("<%= escape_javascript(render(@comment)) %>");

/* Highlight the new comment */
$("#comment_<%= @comment.id %>").effect("highlight", {}, 3000);

/* Reset the comment form */
$("#new_comment")[0].reset();

app/views/comments/destroy.js.erb
/* Eliminate the comment by fading it out */
$('#comment_<%= @comment.id %>').fadeOut();
/* Replace the count of comments */
$("#comments_count").html("<%= pluralize(Comment.count, 'Comentari') %>");

app/views/comments/index.html.erb
<span id="comments_count"><%= pluralize(@comments.count, "Comment") %></span>
<div id="comments">
  <%= render :partial => @comments, :locals => { :list => true } %>
</div>

<hr />

<div id="comment-notice"></div>

<h2>Say something!</h2>
<% form_for Comment.new, :remote => true do |f| %>
	<%= f.label :name, "Your name" %><br />
	<%= f.text_field :name %><br />
	<%= f.label :body, "Comment" %><br />
	<%= f.text_area :body, :rows => 8 %><br />
	<%= f.submit "Add comment" %>
<% end %>