config/routes.rb
Apps::Application.routes.draw do
  get "sessions/new"

  get "users/new"
  get "log_in" => "sessions#new", :as => "log_in" 
  resources :sessions 
  
  namespace :admin do
    resources :books
  end

  resources :articles, :books, :comments
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "books#index"
  resources :users
  get "log_out" => "sessions#destroy", :as => "log_out"
  match 'articles/:id', :to => 'articles#show', :as => "show_article" 
  match 'books/:id', :to => 'books#show', :as => "show_book" 

  match ':controller(/:action(/:id(.:format)))'
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :body, :title, :user_id
  
  validates :title, :presence => true,
                    :uniqueness => true,
                    :length => {:minimum => 1,:maximum => 100}

  has_many :comment, :dependent => :destroy
  belongs_to :user
  scope :rating_is_and_above, lambda {|rating| where("rating > ?", rating)}
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_filter :require_admin_login
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_filter :require_login, :only => [:new, :create, :edit, :update, :destroy]
  
  def show
    @book = Book.find(params[:id])
    @comment = Comment.new
    @comments = @book.comment
  end

  def new
    @book = Book.new  
  end

  def create
    @book= Book.new(params[:book])
    if @book.save
      flash[:notice] = "Book successfully saved"
      redirect_to :action => :index
    else
      flash.now[:notice] = "Book failed to saved"
      render :action => :new
    end
  end
  
  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(params[:book])
      redirect_to books_path, :notice => 'Book was successfully updated.'
    else
      flash[:error] = 'Book was failed to update.'
      render :action => 'edit'
    end
  end

  def index
    @books = Book.all
  end

  def destroy
    Book.destroy(params[:id])
    redirect_to books_path, :notice => 'Book was successfully deleted'
  end

end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Edit book</h1>
<table>
<%= form_for @book do |book| %>
  <tr>
    <td><%= book.label :title %></td>
    <td><%= book.text_field :title %></td>
  </tr>
  <tr>
    <td><%= book.label :body %></td>
    <td><%= book.text_area :body %></td>
  </tr>
  <tr>
    <td><%= book.submit %></td>
  </tr>
<% end %>
</table>

app/views/books/index.html.erb
<h1>List Of books</h1>
<%= flash[:notice] %>
<table class=list_articles>
  <tr>
    <td>Title</td>
    <td>Content</td>
    <td>Option</td>
  </tr>
  <% @books.each do |book|%>
  <tr>
  <td><%= book.title %></td>
  <td><%= book.body %></td>
  <td><%= link_to "Show", book, :class => "no-border" %> <%= link_to 'Edit', edit_book_path(book.id) %> <%= link_to 'Delete', book_path(book.id), :confirm => 'Are you sure want to delete this item?', :method => :delete %>
  </tr>
  <% end %>
</table>
<p><%= link_to "Add new book", new_book_path%></p>

app/views/books/new.html.erb
<h1>New book</h1>
<%= flash[:notice] %>
<table>
<%= form_for @book do |book| %>
  <tr>
    <td><%= book.label :title %></td>
    <td><%= book.text_field :title %></td>
  </tr>
  <tr>
    <td><%= book.label :body %></td>
    <td><%= book.text_area :body %></td>
  </tr>
  <tr>
    <td><%= book.submit %></td>
  </tr>
<% end %>
</table>

app/views/books/show.html.erb
<div class="content">
  <h4><%= @book.title %></h4>
  <table class=list_books>
      <td><%= @book.body %></td>
    </tr>
    <tr> 
      <td><%= @book.created_at %></td>
    </tr>
</div>
<table>
  <%= form_for @comment do |comment| %>
    <td><%= comment.text_area :comment  %></td>
  </tr>
  <tr>
    <td><%= comment.submit %></td>
  </tr>
<% end %>
<%= link_to 'Back to book', books_path %>